"""staff loans and ctc

Revision ID: dd6fae5ee332
Revises: c518ec27e406
Create Date: 2026-10-03 19:46:33.743886

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd6fae5ee332"
down_revision: str | Sequence[str] | None = "c518ec27e406"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_loans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("amount_inr", sa.Integer(), nullable=False),
        sa.Column("disbursed_on", sa.Date(), nullable=False),
        sa.Column("closed_on", sa.Date(), nullable=True),
        sa.Column("outstanding_inr", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_staff_loans_employee_id"), "staff_loans", ["employee_id"], unique=False
    )
    op.add_column("employees", sa.Column("annual_ctc_inr", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "annual_ctc_inr")
    op.drop_index(op.f("ix_staff_loans_employee_id"), table_name="staff_loans")
    op.drop_table("staff_loans")
    # ### end Alembic commands ###
