"""initial schema

Revision ID: abcf77155943
Revises:
Create Date: 2026-10-03 19:00:14.856864

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "abcf77155943"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    postgresql.ENUM("chennai", "karnataka", "usa", name="location").create(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM("active", "notice_period", "exited", name="employment_status").create(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM("employee", "manager", "hr", name="role").create(op.get_bind(), checkfirst=True)
    postgresql.ENUM(
        "pending", "approved", "rejected", "cancelled", name="leave_request_status"
    ).create(op.get_bind(), checkfirst=True)
    postgresql.ENUM("current", "superseded", name="document_status").create(
        op.get_bind(), checkfirst=True
    )
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("employee_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_employee_id"), "audit_log", ["employee_id"], unique=False)
    op.create_index(op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_audit_log_request_id"), "audit_log", ["request_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_uri", sa.String(length=1000), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("policy_key", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column(
            "status", postgresql.ENUM(name="document_status", create_type=False), nullable=False
        ),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("location", postgresql.ENUM(name="location", create_type=False), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_uri"),
    )
    op.create_index(op.f("ix_documents_policy_key"), "documents", ["policy_key"], unique=False)
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_code", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("location", postgresql.ENUM(name="location", create_type=False), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("designation", sa.String(length=100), nullable=False),
        sa.Column("date_of_joining", sa.Date(), nullable=False),
        sa.Column("confirmation_date", sa.Date(), nullable=True),
        sa.Column("prior_experience_months", sa.Integer(), nullable=False),
        sa.Column(
            "employment_status",
            postgresql.ENUM(name="employment_status", create_type=False),
            nullable=False,
        ),
        sa.Column("role", postgresql.ENUM(name="role", create_type=False), nullable=False),
        sa.Column("manager_id", sa.UUID(), nullable=True),
        sa.Column("children_on_record", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_code"),
    )
    op.create_index(op.f("ix_employees_email"), "employees", ["email"], unique=True)
    op.create_table(
        "leave_types",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("annual_entitlement_days", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("quarterly_credit_days", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("carry_forward_max_days", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("accumulation_cap_days", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("encashable", sa.Boolean(), nullable=False),
        sa.Column("balance_tracked", sa.Boolean(), nullable=False),
        sa.Column("policy_reference", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=300), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index"),
    )
    op.create_index(
        "ix_chunks_embedding",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_chunks_tsv", "document_chunks", ["tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "holidays",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location", postgresql.ENUM(name="location", create_type=False), nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location", "holiday_date"),
    )
    op.create_index(op.f("ix_holidays_holiday_date"), "holidays", ["holiday_date"], unique=False)
    op.create_table(
        "hr_tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_hr_tickets_employee_id"), "hr_tickets", ["employee_id"], unique=False)
    op.create_table(
        "leave_balances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_code", sa.String(length=8), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("carried_forward", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("credited", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("used", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leave_type_code"],
            ["leave_types.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "leave_type_code", "year"),
    )
    op.create_index(
        op.f("ix_leave_balances_employee_id"), "leave_balances", ["employee_id"], unique=False
    )
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_code", sa.String(length=8), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("days", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="leave_request_status", create_type=False),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leave_type_code"],
            ["leave_types.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_leave_requests_employee_id"), "leave_requests", ["employee_id"], unique=False
    )
    op.create_table(
        "wfh_days",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("wfh_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "wfh_date"),
    )
    op.create_index(op.f("ix_wfh_days_employee_id"), "wfh_days", ["employee_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wfh_days_employee_id"), table_name="wfh_days")
    op.drop_table("wfh_days")
    op.drop_index(op.f("ix_leave_requests_employee_id"), table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(op.f("ix_leave_balances_employee_id"), table_name="leave_balances")
    op.drop_table("leave_balances")
    op.drop_index(op.f("ix_hr_tickets_employee_id"), table_name="hr_tickets")
    op.drop_table("hr_tickets")
    op.drop_index(op.f("ix_holidays_holiday_date"), table_name="holidays")
    op.drop_table("holidays")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index("ix_chunks_tsv", table_name="document_chunks", postgresql_using="gin")
    op.drop_index(
        "ix_chunks_embedding",
        table_name="document_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("document_chunks")
    op.drop_table("leave_types")
    op.drop_index(op.f("ix_employees_email"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_documents_policy_key"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_audit_log_request_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_employee_id"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    postgresql.ENUM(name="location").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="employment_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="role").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="leave_request_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="document_status").drop(op.get_bind(), checkfirst=True)
